silenced openssl x509 warning using -in
lfs-book/make-ca pull request #30
Opened 2024-03-14 06:31 UTC by Zeckmathederg

Using make-ca, I had the warning for each cert described in issue #29 
I tried using -in but still having it be piped to the openssl x509 command to no avail, so I put the result of the printf(...) to awkinputfile.awktmp so it can be used as an input file and thus silences the warning. 
Does this work at all, both in terms of functionality and how any of you maintainers feel? 

Tested the commit with OpenSSL 3.2.0, compiled using the LFS instructions - no warning regarding stdin, -in, and -new for me.

2024-03-14 07:06 UTC, xry111 commented
Per https://github.com/openssl/openssl/issues/22893 we can use `-in /dev/stdin` to silence the warning w/o introducing temporary file.

2024-03-14 07:07 UTC, xry111 requested changes
.

2024-03-14 07:41 UTC, xry111 commented on help2man
Please remove this change.

2024-03-14 07:46 UTC, Zeckmathederg commented on help2man
Sorry, forgot to run "make clean" before committing and pushing.

2024-03-14 07:47 UTC, xry111 approved these changes
LGTM.

@pierre-labastie Ok for a squash-and-merge and a new release?

2024-06-09 11:01 UTC, xry111 commented
I plan to merge this if there's no objection in a week.

2024-06-09 16:45 UTC, djlucas commented
The proposed fix looks good (assuming it works, have not tested). I wanted to comment on the first proposed fix and note that it revealed another error that probably needs to be addressed (statically named tempfile).

2024-06-11 17:22 UTC, Zeckmathederg commented
Should I add another commit to this PR addressing the statically named tempfile?

2024-06-22 12:34 UTC, merged